# Generated by Django 4.1.3 on 2022-12-01 08:26

import datetime
from django.db import migrations, models
import mod.models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamodel',
            name='filesize',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 26, 6, 180795), editable=False),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mod.models.date_upload_to),
        ),
    ]
