# Generated by Django 4.1.3 on 2022-12-01 08:31

import datetime
from django.db import migrations, models
import mod.models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0002_mediamodel_filesize_mediamodel_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediamodel',
            name='image',
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=mod.models.date_upload_to),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 31, 53, 644353)),
        ),
    ]
