# Generated by Django 4.1.3 on 2022-12-02 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0003_remove_mediamodel_image_mediamodel_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamodel',
            name='original_file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 15, 1, 39, 81232)),
        ),
    ]
