# Generated by Django 4.1.3 on 2022-12-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0004_mediamodel_original_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='timestamp',
            field=models.DateTimeField(default='2022-12-02 23:26:40'),
        ),
    ]
