# Generated by Django 4.1.3 on 2022-12-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0005_alter_mediamodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='timestamp',
            field=models.DateTimeField(default='2022-12-09 14:57:50'),
        ),
    ]
